[Feat]: jet 备份脚本
Byzanteam/jet-deployment pull request #18
Opened 2023-07-10 03:27 UTC by YkeLit

- 使用 velero 对 postgresql 进行持久卷级别备份
- 压缩打包 minio 数据并传输到远端服务器
- 查看 postgresql 备份信息，检查最近一次备份是否成功
- 设定过期时间自动清理过期备份
- 添加备份脚本使用说明
-  添加备份脚本初始化引导

2023-07-10 03:55 UTC, fahchen commented
commit message 不用括号
`[feat]: jet 备份脚本` -> `feat: jet 备份脚本`

2023-07-10 04:02 UTC, fahchen requested changes
这部分最后是集成进 jet 里面，不要单独在外面手动去管理，手动的操作可以提供一些查询接口，恢复接口就好了

2023-07-10 04:02 UTC, fahchen commented on utils/backup/backup.sh
> +PostgresqlDump () {
这些 function 的名字为啥是 pascal 的呢？

2023-07-10 04:02 UTC, fahchen commented on utils/backup/backup.sh
> +}
这个有没可能集成进 jet chart 里面，根据 values 自动执行

2023-07-10 04:02 UTC, fahchen commented on utils/backup/backup.sh
> +EXPIR_EDAY=30
这些值都不能写死吧？

2023-07-12 03:46 UTC, YkeLit commented on utils/backup/backup.sh
> +}
minio 的备份暂时没有想到方法，postgres 的可以

2023-07-13 02:30 UTC, fahchen requested changes

2023-07-13 02:30 UTC, fahchen commented on chart/values.yaml
> +storageLocation: ""
这个值一般填啥呀？

2023-07-13 02:30 UTC, fahchen commented on chart/templates/cronjob/minio-backup-cronjob.yaml
> +                "find ~/{{ .Values.backupDir }} -maxdepth 1 -type f -mtime +{{ .Values.expireDay }} -name '*.tar.gz' -exec  rm -rf {} \;"
这里用 minio 的 client 来操作呢，就不用登陆到某个地方去了
https://min.io/docs/minio/linux/reference/minio-mc.html

2023-07-13 02:31 UTC, fahchen commented on chart/templates/cronjob/minio-backup-cronjob.yaml
> +                "find ~/{{ .Values.backupDir }} -maxdepth 1 -type f -mtime +{{ .Values.expireDay }} -name '*.tar.gz' -exec  rm -rf {} \;"
改成 mc 之后，可以再考虑 velero

2023-07-13 05:16 UTC, YkeLit commented on chart/templates/cronjob/minio-backup-cronjob.yaml
> +                "find ~/{{ .Values.backupDir }} -maxdepth 1 -type f -mtime +{{ .Values.expireDay }} -name '*.tar.gz' -exec  rm -rf {} \;"
这里我想麻烦了，我其实可以挂载两个服务器的持久卷就行了

2023-07-13 07:49 UTC, YkeLit commented on chart/values.yaml
> +storageLocation: ""
这里值是根据 velero 来的

2023-07-13 07:52 UTC, fahchen commented on chart/values.yaml
> +storageLocation: ""
这个值是不是必须得填写？

2023-07-17 03:49 UTC, YkeLit commented on chart/values.yaml
> +storageLocation: ""
这个值不填写也可以，velero 在部署的时候会指定默认的storageLocation

2023-07-17 06:34 UTC, fahchen requested changes
backup 放到一个前缀或者 sub-keys，不要污染其他的

2023-07-17 06:34 UTC, fahchen commented on chart/values.yaml
> +ttl: "720h0m0s"
这部分变量都加 database 的前缀，或者做成 sub-keys

2023-07-17 06:34 UTC, fahchen commented on chart/values.yaml
> +expireDay: "30"
这两个变量也一样，做成前缀或者 sub-keys

2023-07-17 09:55 UTC, YkeLit commented
> backup 放到一个前缀或者 sub-keys，不要污染其他的

我把他们都放到 backup 字段下，这样应该可以吧。

2023-07-18 05:49 UTC, fahchen commented
> > backup 放到一个前缀或者 sub-keys，不要污染其他的
> 
> 
> 
> 我把他们都放到 backup 字段下，这样应该可以吧。

可以的，改成设置了 backup 的才启动那些 job

2023-07-21 09:22 UTC, fahchen requested changes

2023-07-21 09:22 UTC, fahchen commented on chart/templates/velero/postgresql-backup-schedule.yaml
> +{{- with .Values.backup }}
我咋觉得这个不能判断是否开启 backup 呢？

2023-07-21 09:22 UTC, fahchen commented on chart/values.yaml
> +  minioExpireDay: "30"
不要默认值，默认值应该不能正常工作的，需要设置正确才能工作，所以不要给默认值

2023-07-21 09:40 UTC, YkeLit commented on chart/templates/velero/postgresql-backup-schedule.yaml
> +{{- with .Values.backup }}
当backup 控制的时候，这两个备份不会被创建

2023-07-21 09:42 UTC, YkeLit commented on chart/values.yaml
> +  minioExpireDay: "30"
好，这个备份就变成个可选项嘛，需要的时候才加上这个功能

2023-07-21 10:02 UTC, fahchen commented on chart/values.yaml
> +  minioExpireDay: "30"
是的

2023-07-21 10:03 UTC, fahchen commented on chart/templates/velero/postgresql-backup-schedule.yaml
> +{{- with .Values.backup }}
控制是什么意思？

2023-07-24 02:43 UTC, YkeLit commented on chart/templates/velero/postgresql-backup-schedule.yaml
> +{{- with .Values.backup }}
空值

2023-07-24 04:02 UTC, fahchen requested changes
commit message 格式有些问题，重新整理下 commit。其他没问题了

2023-07-25 05:38 UTC, fahchen approved these changes

2023-07-25 08:02 UTC, merged